cars/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.car_hire, name='carhire'),

]

django_raceway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.views.defaults import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('trackdays/', include('trackdays.urls')),
    path('cars/', include('cars.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'home.views.page_not_found'

trackdays/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.track_day_list,
        name='trackdays'),
    path(
        'trackday-booking/<trackday_id>/',
        views.track_day_detail,
        name='booking'),
    path(
        'trackday-request/',
        views.track_day_request,
        name='request'),
    path(
        'experiences/',
        views.experiences,
        name='experiences'),
    path(
        'experiences/<experience_id>/',
        views.experiences_detail,
        name='exp_detail'),
    path(
        'tuition/',
        views.tuition,
        name='tuition'),
    path(
        'tuition/<tuition_id>/',
        views.tuition_detail,
        name='tuition_detail'),
]

trackdays/models.py
from django.db import models
from django.contrib.auth.models import User
from cars.models import Cars
import datetime
from cryptography.fernet import Fernet
import uuid
from django.core.validators import MinValueValidator, RegexValidator


NO = 0
YES = 1
CHOICES = {
    (NO, "No"),
    (YES, "Yes")
}

GP = 0
NATIONAL = 1
INDY = 2
LAYOUT = {
    (GP, "GP"),
    (NATIONAL, "National"),
    (INDY, "Indy"),
}

BRONZE = 0
SILVER = 1
GOLD = 2
LEVELS = {
    (BRONZE, "Bronze"),
    (SILVER, "Silver"),
    (GOLD, "Gold"),
}

DECIBEL_LIMIT = ((0, '98db'), (1, '105db'))
HALF_OR_FULL_DAY = ((0, 'Half-day'), (1, 'Full-day'))


class Trackday(models.Model):

    """
    For storing information for upcoming track days
    """

    layout = models.IntegerField(choices=LAYOUT, default=GP)
    layout_image = models.ImageField(blank=True, null=True)
    date = models.DateField(
        null=False,
        blank=False,
        default=None,
        validators=[
            MinValueValidator(
                datetime.date.today)])
    db_limit = models.BooleanField(choices=DECIBEL_LIMIT, default=0)
    availability = models.IntegerField(default=30)
    base_trackday_price = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return str(f'{self.id}')

    class Meta:
        """ Only one combo of Trackday and date permitted """
        constraints = [
            models.UniqueConstraint(
                fields=['layout', 'date'],
                name='unique_trackday'),
        ]


class TrackdayBooking(models.Model):

    """
    For handling specific track day orders and their optional extras
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    trackday = models.ForeignKey(Trackday, on_delete=models.CASCADE)
    car_hire = models.OneToOneField(
        Cars,
        on_delete=models.CASCADE,
        primary_key=True,
        blank=True)
    full_or_half_day = models.IntegerField(choices=HALF_OR_FULL_DAY, default=0)
    additional_drivers = models.PositiveIntegerField(default=0)
    helmet_hire = models.PositiveIntegerField(default=0)
    tuition = models.PositiveIntegerField(default=0)
    paddock_hire = models.IntegerField(choices=CHOICES, default=NO)

    def __str__(self):
        return str(f'{self.trackday} booking has been made')


class TrackdayRequest(models.Model):

    """
    Model for taking trackday requests
    """

    organiser = models.CharField(max_length=40)
    email = models.EmailField(null=True, blank=True)
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$', message=(
            "Phone number must be entered in the format: '+999999999'."
            + "Up to 15 digits allowed."
        )
    )
    phone_number = models.CharField(
        validators=[phone_regex], max_length=17, blank=True
    )
    date_request = models.DateField(null=True, blank=True)
    full_or_half_day = models.IntegerField(choices=HALF_OR_FULL_DAY, default=0)
    number_of_spaces = models.IntegerField(null=True, blank=True)
    hospitality = models.IntegerField(choices=CHOICES, default=NO)
    pitlanes = models.IntegerField(choices=CHOICES, default=NO)
    db_limit = models.IntegerField(choices=DECIBEL_LIMIT, default=0)
    car_hire_required = models.IntegerField(choices=CHOICES, default=NO)


class Experiences(models.Model):

    """
    Model for the Experience Packages
    """

    title = models.CharField(max_length=150, unique=True, null=False)
    description = models.TextField(max_length=4000)
    itinerary = models.TextField(max_length=4000)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False)

    def save(self, *args, **kwargs):
        if not self.unique_id:
            key = Fernet.generate_key()
            f = Fernet(key)
            self.unique_id = uuid.UUID(bytes=f.encrypt(self.id.bytes))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Experiences"

    def __str__(self):
        return str(self.title)


class Tuition(models.Model):

    """
    Model for the Tuition Packages
    """

    title = models.CharField(max_length=50, unique=True, null=False)
    level = models.IntegerField(choices=LEVELS, default=None)
    description = models.TextField(max_length=4000)
    itinerary = models.TextField(max_length=4000)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    small_image = models.ImageField(null=True, blank=True)
    large_image = models.ImageField(null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False)

    def save(self, *args, **kwargs):
        if not self.unique_id:
            key = Fernet.generate_key()
            f = Fernet(key)
            self.unique_id = uuid.UUID(bytes=f.encrypt(self.id.bytes))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Tuition"

    def __str__(self):
        return str(self.title)

trackdays/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import (
    Experiences, Trackday, TrackdayRequest, TrackdayBooking, Tuition
)
from cars.models import Cars
from django.contrib import messages
from checkout.contexts import basket_contents

trackDayID = 0


def is_availability(trackday_id):
    """
    For checking trackdat availability
    """
    trackday = Trackday.objects.get(id=trackday_id)
    if trackday.availability >= 0:
        return True
    else:
        return False


def track_day_list(request):
    """
    View to render the Track day list menu.
    """
    basket = request.session.get(
        'basket', {'experience': {}, 'tuition': {}, 'trackday': {}})
    trackday_list = Trackday.objects.all()
    basket_trackdays = [x for x in basket['trackday'].keys()]
    available_tracks = [
        x for x in trackday_list if str(
            x.id) not in basket_trackdays]
    isExist = False
    isAvailable = []
    trackdays = Trackday.objects.all()
    for trackday in trackdays:
        trackday_data = {
            "trackday_id": trackday.id,
            "availability": is_availability(trackday.id)
        }
        isAvailable.append(trackday_data)
    if len(basket_trackdays) > 0:
        isExist = True
    context = {
        "trackdays": available_tracks,
        "flag": isExist,
        "available": isAvailable
    }

    return render(request, 'trackdays/trackday-list.html', context)


@login_required
def track_day_detail(request, trackday_id):
    """
    View to render the Track day detail booking page.
    """
    trackday = get_object_or_404(Trackday, pk=trackday_id)
    cars = Cars.objects.all()

    context = {
        "trackday": trackday,
        "cars": cars,
    }

    return render(request, 'trackdays/trackday-detail.html', context)


def track_day_request(request):
    """
    View to render the track day request page.
    """

    if request.method == 'POST':
        # create instance of the trackday request model
        trackday_req = TrackdayRequest()
        trackday_req.organiser = request.POST.get('organiser')
        trackday_req.email = request.POST.get('email')
        trackday_req.phone_number = request.POST.get('tel')
        trackday_req.date_request = request.POST.get('date')
        trackday_req.full_or_half_day = request.POST.get('fullorhalf')
        trackday_req.number_of_spaces = request.POST.get('num_spaces')
        trackday_req.hospitality = request.POST.get('hosp_req')
        trackday_req.pitlanes = request.POST.get('pitlanes')
        trackday_req.db_limit = request.POST.get('db_limit')
        trackday_req.car_hire_required = request.POST.get('carhire')
        # save the information to the database
        trackday_req.save()
        messages.success(
            request,
            'Your Track Day request was succesfully sent!')
        return redirect('home')

    else:
        trackday_req = TrackdayRequest()

    context = {
        'trackday_req': trackday_req,
    }

    return render(request, 'trackdays/trackday-request.html', context)


def tuition(request):
    """
    View to render the tuition information.
    """
    tuition = Tuition.objects.all()

    context = {
        "tuition": tuition
    }

    return render(request, 'trackdays/tuition.html', context)


def tuition_detail(request, tuition_id):
    """
    View to render the tuition details information.
    """
    tuition = get_object_or_404(Tuition, pk=tuition_id)

    context = {
        "tuition": tuition
    }

    return render(request, 'trackdays/tuition-detail.html', context)


def experiences(request):
    """
    View to render the experiences information.
    """

    experiences = Experiences.objects.all()

    context = {
        "experiences": experiences,
    }

    return render(request, 'trackdays/experiences.html', context)


def experiences_detail(request, experience_id):
    """
    View to render the experiences detail page.
    """
    experience = get_object_or_404(Experiences, pk=experience_id)

    context = {
        "experience": experience,
    }

    return render(request, 'trackdays/experience-detail.html', context)

trackdays/templates/trackdays/experience-detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'trackdays/css/exp_detail.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/main-nav.html' %}
<h2 class="text-center mt-4">Experience Detail:</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            <div class="card mb-3">
                <img class="card-img-top" src="{{ experience.image.url }}" alt="picture of cars">
                <div class="card-body mx-auto">
                    <p>{{ experience.title }}</p>
                    <p>{{ experience.description }}</p>
                    {{ experience.itinerary | safe }}
                </div>
                <div class="card-footer border-success d-flex bd-highlight">
                    <div class="p-2 flex-grow-1 bd-highlight d-flex align-items-center">Price: £{{ experience.price }}
                    </div>
                    <form method="POST" action="{% url 'add_exp_to_basket' experience.id %}">
                        {% csrf_token %}
                        <div class="p-2 bd-highlight d-flex align-items-center form-group">
                            <p class="form-label mt-1 pe-1"><span>Quantity:</span></p>
                            <div class="input-group">
                                <button class="increment-qty btn btn-outline-dark rounded-0" data-item_id="{{ experience.id }}"
                                    id="increment-qty_{{ experience.id }}">
                                    <span>
                                        <i class="fas fa-plus quantity-icon"></i>
                                    </span>
                                </button>

                                <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="10"
                                    data-item_id="{{ experience.id }}" id="id_qty_{{ experience.id }}">
                                    
                                <button class="decrement-qty btn btn-outline-dark rounded-0" data-item_id="{{ experience.id }}"
                                    id="decrement-qty_{{ experience.id }}">
                                    <span>
                                        <i class="fas fa-minus quantity-icon"></i>
                                    </span>
                                </button>

                            </div>
                        </div>
                        <div class="p-2 bd-highlight d-flex align-items-center">
                            <input type="submit" class="btn btn-success rounded-0"
                                value="Book the {{ experience.title }}">
                        </div>
                        <div><input type="hidden" name="redirect_url" value="{{ request.path }}"></div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block postloadjs %}
{{ block.super }}
{% include 'trackdays/includes/increment_decrement_script.html' %}
{% endblock %}

trackdays/templates/trackdays/experiences.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'trackdays/css/experiences.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/main-nav.html' %}
<h2 class="m-3 text-center">Experiences:</h2>
<!-- Experience Intro -->
<p class="para mt-4">
  We have 4 bespoke packages to offer to customers who would like to have a closed circuit experience with a specific driving theme. The packages feature a unique set of cars
  tailored to your interests. Many cars here cannot be hired for track days outside of these packages, so it is a unique opportunity to feel the thrill of these amazing machines!
</p>

{% for experience in experiences %}
<!-- Iterates through a list of experience packages -->
<div class="container">
    <div class="experiences row">
        <span>{{ experience.title }}</span>
        {% if experience.image %}
        <div class="image col">
            <img src="{{ experience.image.url }}" alt="Experiences Image">
        </div>
        {% endif %}
        <div class="imgbutton">
            <!-- Link to Experience Details Page-->
            <a class="buttons explore-btn col" href="{% url 'exp_detail' experience.id %}" role="button">Explore</a>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

trackdays/templates/trackdays/trackday-detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'trackdays/css/booking-detail.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/main-nav.html' %}
<div class="heading">
    <a class="backBtn mt-4" href="{% url 'trackdays' %}" >Back to Track Days</a>
    <h2 class="text-center mt-4">Track Day Detail:</h2>

  </div>


<!-- Track day Information Card-->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            <div class="card mb-3">
                <img src="{{ trackday.layout_image.url }}" class="card-img-top"
                    alt="{{ trackday.get_layout_display}} Circuit Map">
                <div class="card-body mx-auto">
                    <h5 class="card-title">{{ trackday.get_layout_display }} Circuit - {{ trackday.date }}</h5>
                    <p class="card-text">{{ trackday.get_db_limit_display }} noise limit</p>
                    <p class="card-text">Base Price: £{{ trackday.base_trackday_price }}</p>
                    <p class="card-text">Currently there are {{ trackday.availability }} spaces left</p>
                </div>
            </div>
        </div>

        <div class="container-fluid mb-2">
            <div class="row">
                <div class="col-lg-8 mx-auto card">
                    <h6 class="text-center"> Select any additional items you wish to add on to your track day below:
                    </h6>

                    <!-- Track Day Booking Form will go here-->

                    <form class="requestForm" method="POST" action="{% url 'add_td_to_basket' trackday.id %}">
                        {% csrf_token %}
                        <div class="formRow">
                            <label for="" class="label">Full or Half Day:</label>

                            <div class="choice">
                                <label for="halfDay" class="me-3 text-center">
                                    <input value="0" type="radio" name="fullHalfDay" id="halfDay">
                                    Half Day - £{% widthratio trackday.base_trackday_price 2 1 %}
                                </label>

                                <label for="fullDay" class="text-center">
                                    <input value="1" type="radio" name="fullHalfDay" id="fullDay" checked>
                                    Full Day - £{{ trackday.base_trackday_price }}
                                </label>
                            </div>
                        </div>

                        <div class="formRow">
                            <label for="paddockhire" class="label">Paddock Hire:</label>

                            <div class="choice">
                                <label for="pitlane" class="me-3 text-center">
                                    <input value="50" type="radio" name="paddockhire" id="pitlane">
                                    Pitlane Paddock - £50
                                </label>

                                <label for="standard" class="text-center">
                                    <input value="0" type="radio" name="paddockhire" id="standard" checked>
                                    Standard Paddock - £0
                                </label>
                            </div>
                        </div>

                        <div class="formRow">
                            <label for="carhire" class="label">Car Hire:</label>

                            <div class="choice">
                                <select name="carhire" id="carhire" class="border-2 border-dark me-5">
                                    {% for car in cars %}
                                    <option value="{{ car.id }}">{{ car.make }} {{ car.model }}
                                        {% if car.variant %}{{ car.variant }} {% endif %} - £{{ car.cost_to_hire }}
                                    </option>
                                    {% endfor %}
                                </select>
                                <label id="byoc" for="" class="text-center pt-3">- Or select "None" to bring your own car!</label>
                            </div>
                        </div>

                        <div class="formRow">
                            <label for="" class="label">Additional Drivers:</label>

                            <div class="choice">
                                <input class="px-2 add" type="button" onclick="incrementDriver()" value="+">
                                <input class="border-2 border-dark" type="number" name="driver-number" value=0 id="driver-number" min="0" max="4">
                                <input class="px-2 minus" type="button" onclick="decrementDriver()" value="-">
                                <label for="driver-number" class="text-center ms-3">- £10 per person (Up to 4 max)</label>
                            </div>
                        </div>

                        <div class="formRow">
                            <label for="" class="label">Helmet Hire:</label>

                            <div class="choice">
                                <input class="px-2 add" type="button" onclick="incrementHelValue()" value="+">
                                <input class="border-2 border-dark" type="number" name="helmet-number" value=0 id="helmet-number" min="0" max="4">
                                <input class="px-2 minus"type="button" onclick="decrementHelValue()" value="-">
                                <label for="helmet-number" class="text-center ms-3">- £10 per person (Up to 4 max)</label>
                            </div>
                        </div>

                        <div class="formRow">
                            <label for="" class="label">Tuition:</label>

                            <div class="choice">
                                <input class="px-2 add" type="button" onclick="incrementTuitionValue()" value="+">
                                <input class="border-2 border-dark" type="number" name="tuition-number" value=0 id="tuition-number" min="0" max="4">
                                <input class="px-2 minus" type="button" onclick="decrementTuitionValue()" value="-">
                                <label class="ms-3" for="tuition-number">- £25 per person (Up to 4 max)</label>
                            </div>
                        </div>

                        <div class="btns">
                            <button type="submit" class="addToBasketBtn">Add to Basket</button>
                            <!-- <button class="checkoutBtn">Checkout</button> -->
                        </div>
                    </form>

                    <div class="container-fluid mb-2">
                        <div class="row d-flex justify-content-end">
                            <div class="col-4 col-lg-3 card border-success">
                                <div class="card-body">
                                  <h6>Total: <span id="total-price" class="fs-4"></span></h6>  
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- On submit, the order is stored in the users basket until they are ready to checkout-->
                </div>

            </div>
        </div>


    {% endblock %}

{% block postloadjs %}

<script type="text/javascript">
const driverTotalNumber = document.getElementById("driver-number");
const helmetTotalNumber = document.getElementById("helmet-number");
const tuitionTotalNumber = document.getElementById("tuition-number");
const incrementDriver = () => {
if (driverTotalNumber.value < 4) {
driverTotalNumber.value = Number(driverTotalNumber.value) + 1;
}
updatePrice();
};
const decrementDriver = () => {
if (driverTotalNumber.value > 0) {
driverTotalNumber.value = Number(driverTotalNumber.value) - 1;
}
updatePrice();
};
const incrementHelValue = () => {
if (helmetTotalNumber.value < 4) {
helmetTotalNumber.value = Number(helmetTotalNumber.value) + 1;
}
updatePrice();
};
const decrementHelValue = () => {
if (helmetTotalNumber.value > 0) {
helmetTotalNumber.value = Number(helmetTotalNumber.value) - 1;
}
updatePrice();
};
const incrementTuitionValue = () => {
if (tuitionTotalNumber.value < 4) {
tuitionTotalNumber.value = Number(tuitionTotalNumber.value) + 1;
}
updatePrice();
};
const decrementTuitionValue = () => {
if (tuitionTotalNumber.value > 0) {
tuitionTotalNumber.value = Number(tuitionTotalNumber.value) - 1;
}
updatePrice();
};

const price = document.getElementById("total-price");
const fullHalfDay = document.getElementsByName("fullHalfDay");
const paddockhire = document.getElementsByName("paddockhire");
const carhire = document.getElementById("carhire");
const updatePrice = () => {
  let total = 0;

  for (let i = 0; i < fullHalfDay.length; i++) {
    if (fullHalfDay[i].checked) {
if(Number(fullHalfDay[i].value)==0){
    let lbl=document.querySelector('label[for="halfDay"]');
    let value = parseInt(lbl.textContent.split(" - £")[1]);
    total+=value;
}else if(Number(fullHalfDay[i].value)==1){
    let lbl=document.querySelector('label[for="fullDay"]');
    let value = parseInt(lbl.textContent.split(" - £")[1]);
    total+=value;

}
    }
  }

  for (let i = 0; i < paddockhire.length; i++) {
    if (paddockhire[i].checked) {
      total += Number(paddockhire[i].value);
    }
  }

  // Add the price of the selected car hire
  if (carhire.value !== "") {
    let selectedOption = carhire.options[carhire.selectedIndex];
    let optionText = selectedOption.text;
    let carPrice = parseFloat(optionText.match(/£(\d+\.\d+)/)[1]);
    total += carPrice;
  }
total += Number(driverTotalNumber.value) * 10;
total += Number(helmetTotalNumber.value) * 10;
total += Number(tuitionTotalNumber.value) * 25;

price.innerHTML = "Total Price: £" + total.toFixed(2);
};

for (let i = 0; i < fullHalfDay.length; i++) {
  fullHalfDay[i].addEventListener("change", updatePrice);
}
for (let i = 0; i < paddockhire.length; i++) {
  paddockhire[i].addEventListener("change", updatePrice);
}
carhire.addEventListener("change", updatePrice);
updatePrice();

</script>

{% endblock %}

trackdays/templates/trackdays/trackday-list.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'trackdays/css/trackdays.css' %}">
{% endblock %}


{% block content %}
{% include 'includes/main-nav.html' %}

<h2 class="m-3 text-center">Track Days</h2>
<!-- Images of the 3 different Track Day Layouts -->
<p class="m-3 text-center">Book by Configurations:</p>

<div class="configuration">
    <div class="content">
        <img src="{% static 'images/main_images/circuit-gp-layout.png' %}" alt="GP International Circuit Layout map">
        <span class="contentCaption">GP International</span>
    </div>

    <div class="content">
        <img src="{% static 'images/main_images/circuit-national-layout.png' %}" alt="National Circuit Layout map">
        <span class="contentCaption">National</span>
    </div>

    <div class="content">
        <img src="{% static 'images/main_images/circuit-indy-layout.png' %}" alt="Indy Circuit Layout map">
        <span class="contentCaption">Indy</span>
    </div>
</div>

<h3 class="text-center mt-5 fs-2 mb-4">Upcoming Trackdays</h3>
<!-- Trackday table/list -->
<div style="overflow-x:auto;" class="trackDayTable">
    <table class="table table-hover">
        <tr>
            <!-- Table Headers -->
            <th>Date</th>
            <th>Layout</th>
            <th>Db limit</th>
            <th>Availability</th>
            <th>Price*</th>
            <th></th>
            {% for trackday in trackdays %}
            <tr>
                <td>{{ trackday.date }}</td>
                <td>{{ trackday.get_layout_display }}</td>
                <td>{{ trackday.get_db_limit_display }}</td>
                <td>{{ trackday.availability }}</td>
                <td class="remain"><span>£{{ trackday.base_trackday_price }}</span></td>
                <!-- Link to booking page -->
                {% if user.is_authenticated %}
                    {% if flag %}
                        <td><button class="book-btn">You can only book 1 at a time.</button></td>              
                    {% else %} 
                        {% for track in available %}
                            {% if track.trackday_id == trackday.id %}
                                {% if track.availability == True %}
                                    <td><div class="book-btn"><a class="text-decoration-none text-reset" href="{% url 'booking' trackday.id %}">Book</a></div></td> 
                                {% else %}
                                    <td class="full"><span>Full</span></td>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% else %} 
                    <td><div class="book-btn"><a class="text-decoration-none text-reset" href="{% url 'account_login' %}">Log in to Book</a></div></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <p class="text-end">*prices before any options added to booking</p>
        </div>
    </div>
</div>

<!-- Button links to Track Day Request Form Page -->
<div class="requestTrack mt-4">
    <span>Want to organise your own Trackday? Click Here</span>
    <a href="{% url 'request' %}">Request a Track day</a>
</div>

{% endblock %}

trackdays/templates/trackdays/tuition.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'trackdays/css/tuition.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/main-nav.html' %}
<!-- Tuition Intro -->
<h2 class="m-3 text-center">Tuition:</h2>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <p class="m-3 para mt-4">
        Django Raceway now offers 3 different tuition packages to enhance your driving abilites, which you can take to
        the
        track to improve your car control and laptimes.
      </p>
    </div>
  </div>
</div>

{% for item in tuition %}
<!-- Tuition items list -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 images">
      <!-- Tuition Level-->
      <h4>{{ item.get_level_display }}</h4>
      <!-- Both Tuition Images-->
      <img class="image img-small" src="{{ item.small_image.url }}" alt="{{ item.get_level_display }} Trophy">
      <div class="imgbutton">
        <img class="w-100 h-100" src="{{ item.large_image.url }}" alt="A racing driver about to get in to his car">
        <!-- Button link to details page -->
        <a class="btn explore-btn col" href="{% url 'tuition_detail' item.id %}" role="button">Explore</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}